version: "3.1"

services:
  api:
    build:
      context: ./api
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules # This is the only change
    env_file:
      - .env
    command: npm run start:$STAGE
    ports:
      - 3001:3000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
